apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app
  labels:
    app: netflix-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-app
  template:
    metadata:
      labels:
        app: netflix-app
    spec:
      containers:
      - name: netflix-app
        image: chrisdcosta.azurecr.io/netflix:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: netflix-app
  labels:
    app: netflix-app
spec:
  # type: NodePort
  # ports:
  # - port: 80
  #   targetPort: 80
  #   nodePort: 30007
  # selector:
  #   app: netflix-app
  selector:
    app: netflix-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer 